services:
  
  spring-web:
    build:
      context: .
    container_name: spring-web-app
    ports:
      - 8080:8080
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-web-app
    environment:
      PGADMIN_DEFAULT_EMAIL: avery@stinkbox.net
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment: 
      POSTGRES_USER: avery
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring-web
    ports:
      - 5432:5432   
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  pgadmin:

# healthcheck:
# test: ["CMD-SHELL", "pg_isready"]
# interval: 1s
# timeout: 5s
# retries: 10      
